[tools]
rust = "1.96"

[tasks.build]
run = "cargo build"

[tasks.run]
run = "cargo run --"

[tasks.test]
run = "cargo test"

[tasks.fmt]
run = "cargo fmt"

[tasks.check]
run = ["cargo fmt --check", "cargo clippy -- -D warnings", "cargo test"]
